name: ci

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: npm i -g --force corepack && corepack enable
      - uses: actions/setup-node@v5
        with: { node-version: lts/*, cache: pnpm }
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm vitest
